apps/blog/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^blog/', blog, name='blog'),
    url(r'^archive/', archive, name='archive'),
    url(r'article/', article, name='article'),
    url(r'^comment_post/', comment_post, name='comment_post'),
    url(r'^tags/', tag_article, name='tag_name'),
]

apps/dailylife/urls.py
from django.conf.urls import url
from dailylife import views


urlpatterns = [
    url(r'life/', views.life, name='life')
]

apps/share/urls.py
from django.conf.urls import url
from share import views


urlpatterns = [
    url(r'^sharesomething/', views.shareSomething, name='share'),
]

newproject/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import serve
from django.conf.urls.static import static
from django.conf import settings
# from django.contrib import admin
import xadmin
import django

urlpatterns = [
    url(r'^xadmin', xadmin.site.urls),
    url(r'^home/', include('home.urls')),
    url(r'^share/', include('share.urls')),
    url(r'^daily/', include('dailylife.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}, name='static'),
    url(r'^ueditor/',include('DjangoUeditor.urls')),

    # url(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}, name='upload_pic')
]

apps/blog/models.py
# -*- coding:utf-8 -*-
from django.db import models
from DjangoUeditor.models import UEditorField
# Create your models here.


# 标签
class TagModel(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )
    tag = models.CharField(max_length=30, verbose_name='标签')

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.tag

    def __unicode__(self):
        return self.tag


# 广告
class AdModel(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )

    adImage = models.ImageField(upload_to='ad/', default='', verbose_name='图片链接')

    class Meta:
        verbose_name = '广告'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.adImage


# 自定义一个文章model的管理器
class ArticleManager(models.Manager):
    def distinct_date(self):
        distinct_date_list = []
        date_list = self.values('date_publish')
        for date in date_list:
            date = date['date_publish'].strftime('%Y/%m')
            if date not in distinct_date_list:
                distinct_date_list.append(date)
        return distinct_date_list


# 文章
class ArticleModel(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )

    title = models.CharField(max_length=50, verbose_name='文章标题', blank=False, null=False, default='')
    image = models.ImageField(upload_to='blog/', default='')
    content = UEditorField(verbose_name='博客内容',
                           width=700,
                           height=400,
                           toolbars='full',
                           imagePath='ueditor/images/',
                           filePath='ueditor/files/',
                           upload_settings={'imageMaxSizing': 1024000}, blank=False, null=False, default='')
    click_count = models.IntegerField(default=0, verbose_name='点击次数')
    is_recommend = models.BooleanField(default=False, verbose_name='是否推荐')
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    tag = models.ManyToManyField(TagModel, verbose_name='标签')

    objects = ArticleManager()

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-date_publish']

    def __str__(self):
        return self.title


# 评论模型
class CommentModel(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )
    name = models.CharField(max_length=50, blank=False, null=False, default='', verbose_name='姓名')
    email = models.EmailField(max_length=50, blank=True, null=True, verbose_name='邮箱地址')
    content = UEditorField(verbose_name='评论内容',
                           width=700,
                           height=400,
                           toolbars='full',
                           imagePath='ueditor/images/',
                           filePath='ueditor/files/',
                           upload_settings={'imageMaxSizing': 1024000},
                           default='')
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name='发布时间')
    pid = models.IntegerField(verbose_name='pid', default='0')
    article = models.ForeignKey(ArticleModel, blank=True, null=True, verbose_name='文章')

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name
        ordering = ['-date_publish']

    def __unicode__(self):
        return str(self.id)

apps/dailylife/models.py
from django.db import models

# Create your models here.


# 日常生活
class DailyLifeModel(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )
    dClass = models.CharField(max_length=50, blank=False, null=False, verbose_name='类')
    dSmallImage = models.ImageField(upload_to='dailylife/small/', default='', verbose_name='小图片')
    dLargerImage = models.ImageField(upload_to='dailylife/large/', default='', verbose_name='大图片')
    dContent = models.CharField(max_length=1000, blank=False, null=False, verbose_name='内容', default='')

    class Meta:
        verbose_name = verbose_name_plural = "日常生活"
        ordering = ["id"]

    def __unicode__(self):
        return self.dContent

apps/share/models.py
from django.db import models

# Create your models here.


# 推荐电影
class MovieModel(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )
    mImage = models.ImageField(upload_to='movie/', default='', verbose_name='图片路径')
    mComment = models.CharField(max_length=1000, blank=False, null=False, verbose_name='电影评价', default='')
    mName = models.CharField(max_length=50, blank=False, null=False, verbose_name='电影名', default='')
    mUrl = models.URLField(max_length=100, blank=False, null=False, verbose_name='电影连接', default='')

    class Meta:
        verbose_name = verbose_name_plural = '电影推荐'
        ordering = ['id']

    def __unicode__(self):
        return self.mName


# 推荐书籍1
class FirstBookModel(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )
    bClassFirst = models.CharField(max_length=50, blank=False, null=False, default='')
    bClassSecond = models.CharField(max_length=50, blank=False, null=False, default='')
    bName = models.CharField(max_length=50, blank=False, null=False, verbose_name='书名', default='')
    bImage = models.ImageField(upload_to='book/', default='', verbose_name='图片路径')
    bComment = models.CharField(max_length=1000, blank=False, null=False, verbose_name='书籍评价', default='')
    bAuthor = models.CharField(max_length=50, blank=False, null=False, verbose_name='书籍作者', default='')
    bUrl = models.URLField(max_length=100, blank=False, null=False, verbose_name='书籍连接', default='')

    class Meta:
        verbose_name = verbose_name_plural = '书籍推荐1'
        ordering = ['id']

    def __unicode__(self):
        return self.bName


# 推荐书籍1
class SecondBookModel(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )
    bName = models.CharField(max_length=50, blank=False, null=False, verbose_name='书名', default='')
    bImage = models.ImageField(upload_to='book/', default='', verbose_name='图片路径')
    bComment = models.CharField(max_length=5000, blank=False, null=False, verbose_name='书籍评价', default='')
    bAuthor = models.CharField(max_length=50, blank=False, null=False, verbose_name='书籍作者', default='')
    bUrl = models.URLField(max_length=100, blank=False, null=False, verbose_name='书籍连接', default='')

    class Meta:
        verbose_name = verbose_name_plural = '书籍推荐2'
        ordering = ['id']

    def __unicode__(self):
        return self.bName

apps/blog/forms.py
from django import forms


class CommentForm(forms.Form):
    '''
    评论表单
    '''
    name = forms.CharField(widget=forms.TextInput(attrs={"id": "author", "class": "comment_input",
                                                           "required": "required", "size": "25", "tabindex": "1"}),
                             max_length=50, error_messages={"required": "username不能为空", })
    email = forms.EmailField(widget=forms.TextInput(attrs={"id": "email", "type": "email", "class": "comment_input",
                                                           "required": "required", "size": "25", "tabindex": "2"}),
                             max_length=50, error_messages={"required": "email不能为空", })
    phone = forms.URLField(widget=forms.TextInput(attrs={"id": "url", "type": "", "class": "comment_input",
                                                       "size": "25", "tabindex": "3"}),
                         max_length=100, required=False)
    comment = forms.CharField(widget=forms.Textarea(attrs={"id": "comment", "class": "message_input",
                                                           "required": "required", "cols": "25",
                                                           "rows": "5", "tabindex": "4"}),
                              error_messages={"required": "评论不能为空", })
    article = forms.CharField(widget=forms.HiddenInput())

apps/blog/views.py
# -*- coding:utf-8-*-
from django.shortcuts import render, redirect
from .models import *
from django.core.paginator import Paginator, InvalidPage, EmptyPage,PageNotAnInteger
from django.views import View
from .forms import *
# Create your views here.


def global_settings(request):
    # 获取标签信息
    tag_list = TagModel.objects.all()

    # 广告信息获取
    ad_list = AdModel.objects.all()

    # 文章归档
    archive_list = ArticleModel.objects.distinct_date()
    return locals()


def blog(request):
    try:
        # 文章信息获取
        article_list = ArticleModel.objects.all()

        # 分页
        paginator = Paginator(article_list, 1)
        try:
            page = int(request.GET.get('page', 1))
            article_list = paginator.page(page)
        except (EmptyPage, InvalidPage, PageNotAnInteger):
            article_list = paginator.page(1)
    except Exception as e:
        pass
    return render(request, 'blog.html', locals())


def archive(request):
    try:
        year = request.GET.get('year', None)
        month = request.GET.get('month', None)

        # 归档文章获取
        article_list = ArticleModel.objects.filter(date_publish__icontains=year+'-'+month)
        paginator = Paginator(article_list, 1)
        try:
            page = int(request.GET.get('page', 1))
            article_list = paginator.page(page)
        except (EmptyPage, InvalidPage, PageNotAnInteger):
            article_list = paginator.page(1)
    except Exception as e:
        pass
    return render(request, 'archive.html', locals())


def article(request):
    try:
        # 文章信息获取
        id = request.GET.get('id', None)
        comment_list = CommentModel.objects.filter(pid=id)
        try:
            article = ArticleModel.objects.get(pk=id)
            article.click_count += 1
            article.save(update_fields=['click_count'])
        except ArticleModel.DoesNotExist:
            return render(request, 'failure.html')
    except Exception as e:
        pass
    return render(request, 'blog-item.html', locals())


def comment_post(request):
    try:
        if request.method == 'POST':
            name = request.POST.get("name")
            email = request.POST.get("email")
            id = request.POST.get("id")
            message = request.POST.get("message")
            CommentModel.objects.create(
                name=name,
                email=email,
                pid=id,
                content=message,
            )
    except Exception as e:
        pass
    return redirect(request.META['HTTP_REFERER'])


def tag_article(request):
    try:
        tag = request.GET.get('tag', None)

        # 标签文章获取
        article_list = ArticleModel.objects.get(tag=tag)
        print(type(article_list))
        paginator = Paginator(article_list, 1)
        try:
            page = int(request.GET.get('page', 1))
            article_list = paginator.page(page)
        except (EmptyPage, InvalidPage, PageNotAnInteger):
            article_list = paginator.page(1)
    except Exception as e:
        pass
    return render(request, 'tag.html', locals())

apps/dailylife/views.py
from django.shortcuts import render
from dailylife.models import *
# Create your views here.


def life(request):
    try:
        # 日常生活信息获取
        daily_life_list = DailyLifeModel.objects.all()
    except Exception as e:
        pass

    return render(request, 'dailylife.html', locals())

apps/share/views.py
from django.shortcuts import render
from share.models import *

# Create your views here.


def shareSomething(request):
    try:
        # 获取电影信息
        movie_list = MovieModel.objects.all()

        # 获取书籍信息
        book1_list = FirstBookModel.objects.all()

        book2_list = SecondBookModel.objects.all()
    except Exception as e:
        pass
    return render(request, 'share.html', locals())

templates/archive.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <section id="blog" class="container">
        <div class="center">
            <h2>{{ request.GET.year }}/{{ request.GET.month }}归档文章</h2>
        </div>
        <div class="blog">
            <div class="row">
                 <div class="col-md-8">
                     {% for article in article_list %}
                        <div class="blog-item">
                            <div class="row">
                                 <div class="col-sm-2 text-center">
                                    <div class="entry-meta">
                                        <span id="publish_date">{{ article.date_publish | date:'Y-m-d' }}</span>
                                        <span><i class="fa fa-comment"></i>{{ article.commentmodel_set.all.count  }} 评论</span>
                                        <span><i class="fa fa-heart"></i>{{ article.click_count }} 浏览</span>
                                    </div>
                                </div>
                                <div class="col-sm-10 blog-content">
                                    <a href=""><img class="img-responsive img-blog" src="/static/media/{{ article.image }}" width="100%" alt="" /></a>
                                    <h2>{{ article.title }}</h2>
                                    <a class="btn btn-primary readmore" href="{% url "article" %}?id={{ article.id }}">阅读<i class="fa fa-angle-right"></i></a>
                                </div>
                            </div>
                        </div><!--/.blog-item-->
                     {% endfor %}

                    <ul class="pagination pagination-lg">
                        {% if article_list.has_previous %}
                            <li><a href="?page={{ article_list.previous_page_number }}{% if request.GET.year %}&year={{ request.GET.year }}{% endif %}{% if request.GET.month %}&month={{ request.GET.month }}{% endif %}">&laquo;上一页</a></li>
                        {% else %}
                            <li>&laquo;上一页</li>
                        {% endif %}
                            <li class="active">{{ article_list.number }}/{{ article_list.paginator.num_pages }}</li>
                        {% if article_list.has_next %}
                            <li><a href="?page={{ article_list.next_page_number }}{% if request.GET.year %}&year={{ request.GET.year }}{% endif %}{% if request.GET.month %}&month={{ request.GET.month }}{% endif %}">下一页 &raquo;</a></li>
                        {% else %}
                            <li>下一页 &raquo;</li>
                        {% endif %}
                    </ul><!--/.pagination-->
                </div><!--/.col-md-8-->

                <aside class="col-md-4">
    				<div class="widget archieve">
                        <h3>文章归档</h3>
                        <div class="row">
                            <div class="col-sm-12">
                                <ul class="blog_archieve">
                                    {% for archive in archive_list %}
                                        <li><a href="{% url "archive" %}?year={{ archive | slice:":4" }}&month={{ archive | slice:"5:7" }}"><i class="fa fa-angle-double-right"></i>{{ archive }}</a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div><!--/.archieve-->

                    <div class="widget tags">
                        <h3>标签云</h3>
                        <ul class="tag-cloud">
                            {% for tag in tag_list %}
                                <li><a class="btn btn-xs btn-primary" href="{% url 'tag_name' %}?tag={{ tag.tag }}">{{ tag.tag }}</a></li>
                            {% endfor %}
                        </ul>
                    </div><!--/.tags-->

    				<div class="widget blog_gallery">
                        <h3>广告</h3>
                        <ul class="sidebar-gallery">
                            {% for ad in ad_list %}
                                <li><a href="http://www.w3school.com.cn"><img src="/static/media/{{ ad.adImage }}" alt="" /></a></li>
                            {% endfor %}
                        </ul>
                    </div><!--/.blog_gallery-->
    			</aside>
            </div><!--/.row-->
        </div>
    </section><!--/#blog-->
{% endblock %}

templates/blog-item.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

    <section id="blog" class="container">
        <div class="center">
            <h2>Blog</h2>
        </div>

        <div class="blog">
            <div class="row">
                <div class="col-md-8">
                        <div class="blog-item">
                        <img class="img-responsive img-blog" src="/static/media/{{ article.image }}" width="100%" alt="" />
                            <div class="row">
                                <div class="col-xs-12 col-sm-2 text-center">
                                    <div class="entry-meta">
                                        <span id="publish_date">{{ article.date_publish | date:'Y-m-d' }}</span>
                                        <span><i class="fa fa-comment"></i>{{ article.commentmodel_set.all.count  }} 评论</span>
                                        <span><i class="fa fa-heart"></i>{{ article.click_count }} 浏览</span>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-10 blog-content">
                                    <h2>{{ article.title }}</h2>
                                    <p>{{ article.content | safe}}</p>
                                    <div class="post-tags">
                                        <strong>标签:</strong>
                                        {% for tag in article.tag.all %}
                                            <a href="?tag={{ tag.name }}" rel="tag">{{ tag }}/</a>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div><!--/.blog-item-->

                    {% for comment in comment_list %}
                        <div class="media comment_section">
                                <div class="media-body post_reply_comments">
                                    <h2>{{ comment.name }}</h2>
                                    <h4>{{ comment.date_publish }}</h4>
                                    <p>{{ comment.content | safe }}</p>
                                </div>
                        </div>
                    {% endfor %}<!--/.blog-comment-->


                        <div id="contact-page clearfix">
                            <div class="status alert alert-success" style="display: none"></div>
                            <div class="message_heading">
                                <p>您可以在这里评论</p>
                            </div> 
      
                            <form id="main-contact-form" class="contact-form" name="contact-form" method="post" action="{% url 'comment_post' %}" role="form">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-sm-5">
                                        <div class="form-group">
                                            <label>姓名</label>
                                            <input type="text" class="form-control" required="required" name="name">
                                        </div>
                                        <div class="form-group">
                                            <label>邮箱</label>
                                            <input type="email" class="form-control" required="required" name="email">
                                        </div>
                                        <div class="form-group">
                                            <label>文章ID</label>
                                            <input  class="form-control" name="id">
                                        </div>                    
                                    </div>
                                    <div class="col-sm-7">                        
                                        <div class="form-group">
                                            <label>信息</label>
                                            <textarea name="message" id="message" required="required" class="form-control" rows="8"></textarea>
                                        </div>                        
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-primary btn-lg" required="required">提交</button>
                                        </div>
                                    </div>
                                </div>
                            </form>     
                        </div><!--/#contact-page-->
                    </div><!--/.col-md-8-->

                <aside class="col-md-4">
    			<div class="widget archieve">
                        <h3>文章归档</h3>
                        <div class="row">
                            <div class="col-sm-12">
                                <ul class="blog_archieve">
                                    {% for archive in archive_list %}
                                        <li><a href="{% url "archive" %}?year={{ archive | slice:":4" }}&month={{ archive | slice:"5:7" }}"><i class="fa fa-angle-double-right"></i>{{ archive }}</a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div><!--/.archieve-->

                    <div class="widget tags">
                        <h3>标签云</h3>
                        <ul class="tag-cloud">
                            {% for tag in tag_list %}
                                <li><a class="btn btn-xs btn-primary" href="{% url 'tag_name' %}?tag={{ tag.tag }}">{{ tag.tag }}</a></li>
                            {% endfor %}
                        </ul>
                    </div><!--/.tags-->
    				
    				<div class="widget blog_gallery">
                        <h3>广告</h3>
                        <ul class="sidebar-gallery">
                            {% for ad in ad_list %}
                                <li><a href="http://www.w3school.com.cn"><img src="/static/media/{{ ad.adImage }}" alt="" /></a></li>
                            {% endfor %}
                        </ul>
                    </div><!--/.blog_gallery-->
    					
    				
                </aside>     

            </div><!--/.row-->

         </div><!--/.blog-->

    </section><!--/#blog-->
{% endblock %}

templates/blog.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <section id="blog" class="container">
        <div class="center">
            <h2>Blogs</h2>
        </div>
        <div class="blog">
            <div class="row">
                 <div class="col-md-8">
                     {% for article in article_list %}
                        <div class="blog-item">
                            <div class="row">
                                 <div class="col-sm-2 text-center">
                                    <div class="entry-meta">
                                        <span id="publish_date">{{ article.date_publish | date:'Y-m-d' }}</span>
                                        <span><i class="fa fa-comment"></i>{{ article.commentmodel_set.all.count }} 评论</span>
                                        <span><i class="fa fa-heart"></i>{{ article.click_count }} 浏览</span>
                                    </div>
                                </div>
                                <div class="col-sm-10 blog-content">
                                    <a href=""><img class="img-responsive img-blog" src="/static/media/{{ article.image }}" width="100%" alt="" /></a>
                                    <h2>{{ article.title }}</h2>
                                    <a class="btn btn-primary readmore" href="{% url "article" %}?id={{ article.id }}">阅读<i class="fa fa-angle-right"></i></a>
                                </div>
                            </div>
                        </div><!--/.blog-item-->
                     {% endfor %}

                    <ul class="pagination pagination-lg">
                        {% if article_list.has_previous %}
                            <li><a href="?page={{ article_list.previous_page_number }}">&laquo;上一页</a></li>
                        {% else %}
                            <li>&laquo;上一页</li>
                        {% endif %}
                            <li class="active">{{ article_list.number }}/{{ article_list.paginator.num_pages }}</li>
                        {% if article_list.has_next %}
                            <li><a href="?page={{ article_list.next_page_number }}">下一页 &raquo;</a></li>
                        {% else %}
                            <li>下一页 &raquo;</li>
                        {% endif %}
                    </ul><!--/.pagination-->
                </div><!--/.col-md-8-->

                <aside class="col-md-4">
    				<div class="widget archieve">
                        <h3>文章归档</h3>
                        <div class="row">
                            <div class="col-sm-12">
                                <ul class="blog_archieve">
                                    {% for archive in archive_list %}
                                        <li><a href="{% url "archive" %}?year={{ archive | slice:":4" }}&month={{ archive | slice:"5:7" }}"><i class="fa fa-angle-double-right"></i>{{ archive }}</a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div><!--/.archieve-->

                    <div class="widget tags">
                        <h3>标签云</h3>
                        <ul class="tag-cloud">
                            {% for tag in tag_list %}
                                <li><a class="btn btn-xs btn-primary" href="{% url 'tag_name' %}?tag={{ tag.tag }}">{{ tag.tag }}</a></li>
                            {% endfor %}
                        </ul>
                    </div><!--/.tags-->

    				<div class="widget blog_gallery">
                        <h3>广告</h3>
                        <ul class="sidebar-gallery">
                            {% for ad in ad_list %}
                                <li><a href="http://www.w3school.com.cn"><img src="/static/media/{{ ad.adImage }}" alt="" /></a></li>
                            {% endfor %}
                        </ul>
                    </div><!--/.blog_gallery-->
    			</aside>
            </div><!--/.row-->
        </div>
    </section><!--/#blog-->
{% endblock %}

templates/contact-us.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <section id="contact-page">
        <div class="container">
            <div class="center">        
                <h2>提交信息</h2>
                <p class="lead">您也可以通过这里来发送信息给我，我会根据您的联系方式回复您。</p>
            </div> 
            <div class="row contact-wrap">
                <form id="main-contact-form" class="contact-form" name="contact-form" method="post" action="{% url 'add' %}">
                    {% csrf_token %}
                    <div class="col-sm-5 col-sm-offset-1">
                        <div class="form-group">
                            <label>姓名</label>
                            <input type="text" name="name" class="form-control" required="required">
                        </div>
                        <div class="form-group">
                            <label>邮箱</label>
                            <input type="email" name="email" class="form-control" required="required">
                        </div>
                        <div class="form-group">
                            <label>电话</label>
                            <input class="form-control" name="phone">
                        </div>
                                <div class="form-group">
                            <label>日期</label>
                            <input type="text" class="form-control" name="date">
                        </div>
                    </div>
                    <div class="col-sm-5">
                        <div class="form-group">
                            <label>主题</label>
                            <input type="text" name="theme" class="form-control" required="required">
                        </div>
                        <div class="form-group">
                            <label>信息</label>
                            <textarea name="message" id="message" required="required" class="form-control" rows="8"></textarea>
                        </div>                        
                        <div class="form-group">
                            <button type="submit" name="submit" class="btn btn-primary btn-lg" required="required">提交信息</button>
                        </div>
                    </div>
                </form> 
            </div><!--/.row-->
        </div><!--/.container-->
    </section><!--/#contact-page-->
{% endblock %}

templates/failure.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <section id="error" class="container text-center">
        <p>文章不存在</p>
        <a class="btn btn-primary" href="{% url 'my_index' %}">回到主页</a>
    </section><!--/#error-->
{% endblock %}